<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-RJTB1K6" failures="1" tests="7" name="SCRUM-33 test" time="29.314" errors="0" timestamp="2025-04-15T18:19:18 GMT-05:00">
  <testcase classname="Test.TestSet01" name="try1" time="2.792">
    <skipped/>
  </testcase> <!-- try1 -->
  <testcase classname="Test.TestSet01" name="try1" time="3.719">
    <skipped/>
  </testcase> <!-- try1 -->
  <testcase classname="Test.TestSet01" name="try1" time="3.488">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.TestSet01.try1(TestSet01.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- try1 -->
  <testcase classname="Test.TestSet01" name="try2" time="5.425"/>
  <testcase classname="Test.TestSet01" name="try3" time="4.509"/>
  <testcase classname="Test.TestSet01" name="try4" time="4.489"/>
  <testcase classname="Test.TestSet01" name="try5" time="4.282"/>
</testsuite> <!-- SCRUM-33 test -->
